satellite_project/cms_main_project_mysql/core/cms1.0/controllers/BetaxonomyController.php
<?php
/**
 * Backend Taxonomy Controller.
 *
 * @author Tuan Nguyen <nganhtuan63@gmail.com>
 * @version 1.0
 * @package backend.controllers
 *
 */
class BetaxonomyController extends BeController
{
    public function __construct($id, $module = null)
    {
        parent::__construct($id, $module);
        $this->menu = array(
            array('label' => _t('Manage Taxonomy'), 'url' => array('admin'), 'linkOptions' => array('class' => 'button')),
            array('label' => _t('Define Taxonomy'), 'url' => array('create'), 'linkOptions' => array('class' => 'button')),
        );
    }

    /**
     * The function that do Create new Taxonomy
     *
     */
    public function actionCreate()
    {
        $this->render('taxonomy_create');
    }

    /**
     * The function that do Manage Taxonomy
     *
     */
    public function actionAdmin()
    {
        $this->render('taxonomy_admin');
    }

    /**
     * The function that view Taxonomy details
     *
     */
    public function actionView()
    {
        $id = isset($_GET['id']) ? (int) ($_GET['id']) : 0;
        $this->menu = array_merge($this->menu,
            array(
                array('label' => _t('Update this Taxonomy'), 'url' => array('update', 'id' => $id), 'linkOptions' => array('class' => 'button')),
                array('label' => _t('View this Taxonomy'), 'url' => array('view', 'id' => $id), 'linkOptions' => array('class' => 'button')),
            )
        );
        $this->render('taxonomy_view');
    }

    /**
     * The function that update Taxonomy
     *
     */
    public function actionUpdate()
    {
        $id = isset($_GET['id']) ? (int) ($_GET['id']) : 0;
        $this->menu = array_merge($this->menu,
            array(
                array('label' => _t('Update this Taxonomy'), 'url' => array('update', 'id' => $id), 'linkOptions' => array('class' => 'button')),
                array('label' => _t('View this Taxonomy'), 'url' => array('view', 'id' => $id), 'linkOptions' => array('class' => 'button')),
            )
        );
        $this->render('taxonomy_update', array('id' => $id));
    }

    /**
     * The function is to Delete Taxonomy
     *
     */
    public function actionDelete($id)
    {
        GxcHelpers::deleteModel('Taxonomy', $id);
    }

}

satellite_project/cms_main_project_mysql/core/cms1.0/controllers/BetermController.php
<?php
/**
 * Backend Term Controller.
 *
 * @author Tuan Nguyen <nganhtuan63@gmail.com>
 * @version 1.0
 * @package backend.controllers
 *
 */
class BetermController extends BeController
{

    public function __construct($id, $module = null)
    {
        parent::__construct($id, $module);
        $this->menu = array(
            array('label' => _t('Manage Terms'), 'url' => array('admin'), 'linkOptions' => array('class' => 'button')),
            array('label' => _t('Add Term'), 'url' => array('create'), 'linkOptions' => array('class' => 'button')),
        );

    }

    /**
     * The function that do Create new Term
     *
     */
    public function actionCreate()
    {

        $this->render('term_create');
    }

    /**
     * The function that do Manage Term
     *
     */
    public function actionAdmin()
    {
        $this->render('term_admin');
    }

    /**
     * The function that view Term details
     *
     */
    public function actionView()
    {
        $id = isset($_GET['id']) ? (int) ($_GET['id']) : 0;
        $this->menu = array_merge($this->menu,
            array(
                array('label' => _t('Update this Term'), 'url' => array('update', 'id' => $id), 'linkOptions' => array('class' => 'button')),
                array('label' => _t('View this Term'), 'url' => array('view', 'id' => $id), 'linkOptions' => array('class' => 'button')),
            )
        );
        $this->render('term_view');
    }

    /**
     * The function that update Term
     *
     */
    public function actionUpdate()
    {
        $id = isset($_GET['id']) ? (int) ($_GET['id']) : 0;
        $this->menu = array_merge($this->menu,
            array(
                array('label' => _t('Update this Term'), 'url' => array('update', 'id' => $id), 'linkOptions' => array('class' => 'button')),
                array('label' => _t('View this Term'), 'url' => array('view', 'id' => $id), 'linkOptions' => array('class' => 'button')),
            )
        );
        $this->render('term_update', array());
    }

    /**
     * The function is to Delete Term
     *
     */
    public function actionDelete($id)
    {
        Term::ajaxDeleteModel($id);
    }

    /**
     * The function is to Delete Term
     *
     */
    public function actionChangeOrder()
    {
        Term::ajaxChangeOrder();
    }

    /**
     *
     * This function is generate Terms based on Taxonomy Id
     */
    public function actionDynamicParentTerms()
    {
        if (isset($_POST['Term']['taxonomy_id'])) {
            $taxonomy_id = (int) ($_POST['Term']['taxonomy_id']);
        }

        if (isset($_POST['Block']['taxonomy'])) {
            $taxonomy_id = (int) ($_POST['Block']['taxonomy']);
        }

        Term::getTermFromTaxonomy($taxonomy_id);
    }

}

satellite_project/cms_main_project_mysql/core/cms1.0/views/betaxonomy/taxonomy_admin.php
<?php
$this->pageTitle = _t('Manage Taxonomy');
$this->pageHint = _t('Here you can manage your Taxonomy');
$this->widget('cms.widgets.ModelManageWidget', array(
    'model_name' => 'Taxonomy'
));

satellite_project/cms_main_project_mysql/core/cms1.0/views/betaxonomy/taxonomy_create.php
<?php
$this->pageTitle = _t('Add new Taxonomy');
$this->pageHint = _t('Here you can add new Taxonomy for your Content Type');
$this->widget('cms.widgets.object.TaxonomyCreateUpdateWidget');

satellite_project/cms_main_project_mysql/core/cms1.0/views/betaxonomy/taxonomy_update.php
<?php
$this->pageTitle = _t('Update Taxonomy');
$this->pageHint = _t('Here you can update information for current Taxonomy');

$form_create_url = Yii::app()->controller->createUrl('beterm/create', array(
    'embed' => 'iframe',
    'taxonomy' => $id,
    'site' => Yii::app()->controller->site,
));
$form_update_url = Yii::app()->controller->createUrl('beterm/update', array(
    'embed' => 'iframe',
    'taxonomy' => $id,
    'site' => Yii::app()->controller->site,
));
$form_change_order_url = Yii::app()->controller->createUrl('beterm/changeorder', array(
    'site' => Yii::app()->controller->site,
));
$form_delete_url = Yii::app()->controller->createUrl('beterm/delete', array(
    'site' => Yii::app()->controller->site,
));

$this->widget('cms.widgets.object.TaxonomyCreateUpdateWidget', array(
    'form_create_term_url' => $form_create_url,
    'form_update_term_url' => $form_update_url,
    'form_delete_term_url' => $form_delete_url,
    'form_change_order_term_url' => $form_change_order_url,
));

satellite_project/cms_main_project_mysql/core/cms1.0/views/betaxonomy/taxonomy_view.php
<?php
$this->pageTitle = _t('Taxonomy details');
$this->widget('cms.widgets.ModelViewWidget', array(
    'model_name' => 'Taxonomy'
));