satellite/protected/models/Thematics.php
<?php

/**
 * This is the model class for table "thematics".
 *
 * The followings are the available columns in table 'thematics':
 * @property integer $id
 * @property string $title
 * @property integer $active
 */
class Thematics extends CActiveRecord
{
	const CACHE_ID_THEMATICS_CHILDREN = 'Thematics::getListWithChildren()';

	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Thematics the static model class
	 */
	public static function model($className=__CLASS__){
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName(){
		return 'thematics';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules(){
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('title', 'required'),
			array('active', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>255),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, title, active', 'safe', 'on'=>'search'),
		);
	}

	public function getList(){
		return CHtml::listData(self::model()->findAll(array(
			'select' => array('id', 'title'),
			'condition' => 'active=1',
			'order' => 'title ASC'
		)), 'id', 'title');
	}

	/**
	 * Возвращает дерево тематик с их категориями для выпадающего меню
	 * @return array список для выпадающего меню
	 */
	public function getListWithChildren()
	{
		$cacheId = self::CACHE_ID_THEMATICS_CHILDREN;
		if(!($list = Yii::app()->cache->get($cacheId))) {
			$thematics = $this->with('categories')->findAll(array(
				'condition' => 'categories.active=1 AND t.active=1',
				'order' => 't.title ASC'
				));

			$list = array();

			foreach ($thematics as $t) {
				$list['t'.$t->primaryKey] = $t->title;

				if($t->categories) {
					foreach ($t->categories as $c) {
						$list['c'.$c->primaryKey] = ' - ' . $c->title;
					}
				}
			}

			Yii::app()->cache->set($cacheId, $list);
		}

		return $list;
	}

	protected function afterSave()
	{
		// Обновляем кэш
		//Yii::app()->cache->sate(self::CACHE_ID_THEMATICS_CHILDREN, null);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations(){
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'categories' => array(self::HAS_MANY, 'Categories', 'id_thematic')
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels(){
		return array(
			'id' => 'ID',
			'title' => 'Название',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search(){
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.
		$criteria=new CDbCriteria;


		$criteria->compare('id',$this->id);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('active',$this->active);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			'pagination'=>array(
				'pageSize'=>50,
			)
		));
	}
}

satellite/protected/controllers/ThematicsController.php
<?php
class ThematicsController extends Controller{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	//public $layout='//layouts/column2';
	public $layout='//layouts/glp1';


	public function init(){
		if(Yii::app()->user->checkUserRole(User::MODERATOR)){
			$url = Yii::app()->createAbsoluteUrl('/sources/admin');
			$this->redirect($url);
		}
	}
	
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id){
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate(){
		$model=new Thematics;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		// if(isset($_GET['Thematics'])){
		// 	$model->attributes = $_GET['Thematics'];
		// }

		if(isset($_POST['Thematics'])){
			$model->setAttributes($_POST['Thematics'], true);
			// if($model->save()){
			// 	echo 'success';
			// 	Yii::app()->end();
			// }
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('create',array(
			'model'=>$model,
		));

		//Yii::app()->end();

		// $model=new Sources;
		// if(isset($_GET['Sources'])){
		// 	$model->attributes = $_GET['Sources'];
		// 	if(isset($_GET['Sources']['categories'])){
		// 		$model->categories = $_GET['Sources']['categories'];
		// 	}
		// }

		// if(isset($_POST['Sources'])){
		// 	$model->setAttributes($_POST['Sources'], false);
		// 	$model->categories = isset($_POST['Sources']['categories']) ? $_POST['Sources']['categories'] : array();
		// 	if($model->save())
		// 		$this->redirect(array('update','id'=>$model->id));
		// }

		// $this->render('create',array(
		// 	'model'=>$model,
		// ));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id){
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Thematics'])){
			$model->setAttributes($_POST['Thematics'], false);
			// if($model->save()){
			// 	echo 'success';
			// 	Yii::app()->end();
			// }
			if($model->save())
				$this->redirect(array('admin'));
		}

		// $this->renderPartial('update',array(
		// 	'model'=>$model,
		// ));
		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id){
		$this->loadModel($id)->delete();
		$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex(){
		$dataProvider=new CActiveDataProvider('Thematics');
		$dataProvider->pagination->pageSize=50;
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}


	/**
	 * Manages all models.
	 */
/*	public function actionAdmin()
	{
		// $model =  Thematics::model()->findAll(array(
		// 	'select' => array('id', 'title'),
		// 	'condition' => 'active=1',
		// 	'order' => 'title ASC'
		// ));
		$model = new  Thematics('search');
		// $model->unsetAttributes();
		// if(isset($_GET['User'])){
		// 	$model->setAttributes($_GET['User'], false);
		// }

		$this->render('admin',array(
			'data'=>$model,
		));
	}*/

	public function actionAdmin(){
		$data = array();
		$thematics = Thematics::model()->findAll(array(
			'select' => array('id', 'title'),
			'condition' => 'active=1',
			'order' => 'title ASC'
		));

		$ids = array();
		$i = 0;
		foreach($thematics as $thema){
			$data[$thema->id]['text'] = $this->renderPartial('_tree_item', array('type' => 'thematics', 'odd' => $i%2==0, 'data' => $thema), true);
			$ids[$thema->id] = $thema->id;
			$data[$thema->id]['expanded'] = false;
			$i++;
		}

		if(count($ids)){
			$categories = Categories::model()->findAll(array(
			'select' => array('id', 'title', 'id_thematic'),
				'condition' => 'active=1 AND id_thematic IN('.implode(',', $ids).')',
				'order' => 'title ASC'
			));

			$i = 0;
			foreach($categories as $cat){
				$data[$cat->id_thematic]['children'][$cat->id]['text'] = $this->renderPartial('_tree_item', array('type' => 'categories', 'odd' => $i%2==0, 'data' => $cat), true);
				$i++;
			}
		}

		$this->render('admin',array(
			'data'=>$data,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Thematics the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id){
		$model=Thematics::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Thematics $model the model to be validated
	 */
	protected function performAjaxValidation($model){
		if(isset($_POST['ajax']) && $_POST['ajax']==='thematics-form'){
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

satellite/protected/views/thematics/_form.php
	

	<?php $form=$this->beginWidget('CActiveForm', array(
		'id'=>'thematics-form',
		'enableAjaxValidation'=>false,
		'htmlOptions'=>array(
			'class' => 'form-horizontal row-border',
			),
	)); ?>

		<?php echo $form->errorSummary($model); ?>
		<div class="panel-body">
			<div class="form-group">
				<?php echo $form->labelEx($model,'title',array('class'=>'col-sm-2 control-label')); ?>
				<div class="col-sm-8">
					<?php echo $form->textField($model,'title',array('size'=>60,'maxlength'=>255,'class'=>'form-control')); ?>
					<?php echo $form->error($model,'title'); ?>
				</div>
			</div>
		</div>
			

		<div class="panel-footer">
			<div class="row">
				<div class="col-sm-8 col-sm-offset-2">
					<?php echo CHtml::submitButton($model->isNewRecord ? 'Создать' : 'Сохранить', array('class' => 'btn btn-success')); ?>
					<a onclick="javascript:history.back();" class='btn btn-inverse'>назад</a>
				</div>
			</div>
		</div>

	<?php $this->endWidget(); ?>

	

satellite/protected/views/thematics/_tree_item.php
<?php
$updateUrl = '/'.$type.'/update/?id=' . $data->id;
?>
<div class="tree-item-content <?php echo $odd ? ' odd' : '';?>">
	<a href="/sites/admin/?Sites[id_thematic]=<?php echo $type=='thematics'?$data->id:$data->id_thematic.'&Sites[_categories][]='.$data->id;?>"><?php echo $data->title;?></a>
	<span class="thematics-block">
		<?php if ($type=='thematics'): ?>
			<a href="<?php echo '/categories/create/?id_thematic=' . $data->id;?>" class="doManageThematics">
				<span data-tooltip class="has-tip icon-plus" title="Добавить категорию"></span>
			</a>
		<?php endif ?>
		<a href="<?php echo $updateUrl;?>" class="doManageThematics">
			<span data-tooltip class="has-tip icon-pencil" title="Редактировать <?php echo $type=='thematics'?'тематику':'категорию' ?>"></span>
		</a>
		<a href="<?php echo Yii::app()->createUrl('/'.$type.'/delete/', array('id' => $data->id));?>">
			<span data-tooltip class="icon-trash has-tip" title="Удалить <?php echo $type=='thematics'?'тематику':'категорию' ?>"></span>
		</a>
		&nbsp;&nbsp;&nbsp;
		<a href="/sites/create/?Sites[id_thematic]=<?php echo $type=='thematics'?$data->id:$data->id_thematic.'&Sites[_categories][]='.$data->id;?>">
			<span data-tooltip class="icon-file has-tip" title="Добавить сайт"></span>
		</a>
		&nbsp;&nbsp;&nbsp;
		<a href="/sources/admin/?Sources[id_thematic]=<?php echo $type=='thematics'?$data->id:$data->id_thematic.'&Sources[_categories][]='.$data->id;?>">
			<span data-tooltip class="icon-info-sign has-tip" title="Просмотреть источники"></span>
		</a>
		<a href="/sources/create/?Sources[id_thematic]=<?php echo $type=='thematics'?$data->id:$data->id_thematic.'&Sources[_categories][]='.$data->id;?>">
			<span data-tooltip class="icon-plus-sign has-tip" title="Добавить источник"></span>
		</a>
	</span>
</div>

satellite/protected/views/thematics/admin.php
<?php
/* @var $this ThematicsController */
/* @var $model Thematics */
$this->breadcrumbs=array(
	'Тематики'
);

$this->menu = array(
	array(
		'label' => 'Создать тематику', 
		'url' => '/thematics/create',
		'linkOptions' => array(
			'class' => 'doManageThematics'
		)
	)
);

$this->pageTitle = 'Тематики';
?>
<style type="text/css">
.thematics-block{ visibility: hidden;}
</style>
<!-- <div class="panel panel-sky" data-widget='{"draggable": "true"}'> -->
<div class="panel panel-default">
    <div class="panel-heading">
    	<h2>Тематики</h2>
    </div>
  	<div class="panel-body">
		<?php if(Yii::app()->user->checkAccess('Thematics.create')) { ?>
    	<h2><a href="/thematics/create" class="btn btn-success">Создать</a></h2>
		<?php } ?>
    	<table class="table table-hover m-n" >
            <thead>
                <tr>
                    <th style="padding-right:100px">Категория</th>
                    <!-- <th>Population (1000s)</th> -->
                    <th>Подкатегория</th>
                    <th>изменить</th>
                    <th>удалить</th>
                    <th>источники</th>
                    <th>добавить источник</th>
                    <th>добавить сайт</th>
                </tr>
            </thead>
            <tbody>

            	<?php
            	foreach ($data as $key => $value) {
					echo "<tr><td style='font-weight: bold'>".$value["text"]."</td>";

					echo '<td><a  href="/categories/create/?id_thematic='.$key.'"><i style=\'color: #000\' title="создать подкатегорию" class="fa fa-folder-open-o"></i> создать</a>';

					echo "</td>";
					echo '<td><a href="/thematics/update/?id='.$key.'"><i style=\'color: #000\' title="редактировать тематику" class="fa fa-wrench"></i></a></td>';
					echo '<td><a href="/thematics/delete?id='.$key.'"><i style=\'color: #000\' title="удалить тематику" class="fa fa-trash-o"></i></a></td>';
					echo '<td><a href="/sources/admin/?Sources[id_thematic]='.$key.'"><i style=\'color: #000\' title="посмотреть/управлять предложенными источниками"class="fa fa-eye"></i></a></td>';
					echo '<td><a href="/sources/create/?Sources[id_thematic]='.$key.'"><i style=\'color: #000\' title="создать предложенный источник источник" class="fa fa-plus"></i></a></td>';
					echo '<td><a href="/sites/create/?Sites[id_thematic]='.$key.'"><i style=\'color: #000\' title="создать сайт по определенной тематике" class="fa fa-plus"></i></a></td>';
					echo "</tr>";
					if(isset($value['children']))
					 	tree($value['children']);
				}
            	?>

            </tbody>
        </table>
    </div>
</div>
<!-- </div> -->

<?php
//echo print_r($data,true);
// $this->widget('CTreeView', array(
// 	'id' => 'thematics-tree',
// 	'htmlOptions' => array(
// 		'class' => 'thematics-tree',
// 		),
// 	'data' => $data
// ));


function tree($data){

	// echo '<table class="table table-striped m-n" >
	//         <tbody>';
	
	foreach ($data as $key => $v) {
			echo "<tr><td colspan=2 class=\"pod-td\" style=\"padding-left: 25px; color: #000\" ><span> ".$v["text"]."</span></td>";
			echo '<td><a href="/categories/update/?id='.$key.'"><i style=\'color: #000\' title="редактировать подкатегорию" class="fa fa-wrench"></i></a></td>';
			echo '<td><a href="/categories/delete?id='.$key.'"><i style=\'color: #000\' title="удалить подкатегорию" class="fa fa-trash-o"></i></a></td>';
			echo '<td><a href="/sources/admin/?Sources[id_thematic]='.$key.'"><i style=\'color: #000\' title="управлять предложенными источниками" class="fa fa-eye"></i></a></td>';
			echo '<td><a href="/sources/create/?Sources[id_thematic]='.$key.'"><i style=\'color: #000\' title="создать источник" class="fa fa-plus"></i></a></td>';
			echo '<td><a href="/sites/create/?Sites[id_thematic]='.$key.'"><i style=\'color: #000\' title="создать сайт"class="fa fa-plus"></i></a></td>';
			echo "</tr>";
			// if(isset($v['children']))
			// 	tree($v);
	}	
	// echo "</tbody>";
	// echo "</table>";
}
?>

satellite/protected/views/thematics/create.php
<?php
/* @var $this ThematicsController */
/* @var $model Thematics */
$this->breadcrumbs=array(
	'Создание'
);
?>
<div class="panel panel-default">
    <div class="panel-heading"><h2>Создание тематики</h2></div>
	<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
</div>

satellite/protected/views/thematics/index.php
<?php
/* @var $this ThematicsController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Thematics',
);

$this->menu=array(
	array('label'=>'Create Thematics', 'url'=>array('create')),
	array('label'=>'Manage Thematics', 'url'=>array('admin')),
);
?>

<h1>Thematics</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

satellite/protected/views/thematics/update.php
<?php
$this->breadcrumbs=array(
	'Редактирование тематики'
);
?>

<div class="panel panel-default">
    <div class="panel-heading">
    	<h2>Редактирование тематики</h2>
    </div>
  	<div class="panel-body no-padding">
        
<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

	</div>
</div>

satellite/protected/views/thematics/view.php
<?php
/* @var $this ThematicsController */
/* @var $model Thematics */

$this->breadcrumbs=array(
	'Thematics'=>array('index'),
	$model->title,
);

$this->menu=array(
	array('label'=>'List Thematics', 'url'=>array('index')),
	array('label'=>'Create Thematics', 'url'=>array('create')),
	array('label'=>'Update Thematics', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Thematics', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Thematics', 'url'=>array('admin')),
);
?>

<h1>View Thematics #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'title',
		'active',
	),
));